### ISSUE TITLE
Loading private Documents doesn't work

### ISSUE THREAD

**Issue by m3kkasi** [fastread/src#5]
Hello,

loading the sample files in workspace > data all work great, but when i try to load a different .csv file, i get the following error:

![image](https://user-images.githubusercontent.com/18071002/104965039-17181c80-59de-11eb-9b8a-18e254d4d62b.png)

The .csv file i try to load looks like this:
Document Title,Abstract,Year,PDF Link
...
...
...
...

This ist just a small sample file to test the programm, but you stated in your README, that loading csv files fromm IEEEexplore should also be possible, with them i get exactly the same error.

I hope you can help me! :)

**Comment by azhe825** [comment]
@artwork95 Can you send me the sample file that produces the same error? You can send it to this email: zyu9@ncsu.edu

**Comment by m3kkasi** [comment]
This problem is closed. There were problems with different formats of .csv-Files!
For anyone in the future with the same problem: Try using google spreadsheets instead of excel, that helped in my case.

Thanks again for the fast reply.
