### ISSUE TITLE
Various issues loading files

### ISSUE THREAD

**Issue by michaelreuter1** [fastread/src#6]
I can start the server, but cannot load some of the files. I first tried "Radjenovic.csv", which worked perfectly. But the I tried "Hall.csv", which does not succeed. It shows the following in the console:

[2021-03-14 20:46:35,133] ERROR in app: Exception on /load [POST]
Traceback (most recent call last):
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "index.py", line 28, in load
    pos, neg, total = target.get_numbers()
  File "./util\mar.py", line 114, in get_numbers
    total = len(self.body["code"]) - self.last_pos - self.last_neg
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py", line 2950, in __getitem__
    if self.columns.is_unique and key in self.columns:
  File "C:\Users\Michael Reuter\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py", line 5176, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas\_libs\properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
AttributeError: 'NoneType' object has no attribute 'axes'
127.0.0.1 - - [14/Mar/2021 20:46:35] "←[35m←[1mPOST /load HTTP/1.1←[0m" 500 -

I additionally tried loading a self-generated "text.csv" which contains the following text, and creates the error message "Load file failed!! Must put file under workspace/data" in the browser although the files is exactly where it should be (and where the others are).

Contents of test.csv:

Document Title;Abstract;Year;PDF Link;label
Trait-Based Personality Profile of Software Programmers: A Study on Pakistan's Software Industry;Software engineering is a human-centric activity and humans are what their personalities dictate. Personality of the programmers determines the proficiency in programming, the quality of the code as well as the satisfaction of the programmer. However, the personality research in software engineering is still scarce, inconclusive and feeble. Moreover, most of the research is conducted in Western countries. Furthermore, most of the existing personality profiles are based on personality type and not the traits. Hence, the present research attempts to develop a personality profile of the programmers working in a south Asian country, namely Pakistan based on personality traits. With the help of the data collected from 294 programmers working in GSD based companies in Pakistan, the results showed that programmers largely possess the traits of agreeableness and conscientiousness whereas neuroticism is the least dominant trait among programmers.;2018;https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8699231;no
Making programmer suitable for team-leader: Software team composition based on personality types;The profuse use of software has turned the world into global village where everything is accessible at finger tips. The past studies have confirmed the rapid increase in the demand of software whereas its quality supply has drastically decreased to 6%. As high demand and low supply normally generate numerous problems, many researchers, therefore, have raised their concern to develop software affordable, less time consuming and feasible to achieve organisational ends. The findings of the past research studies have determined the fact that besides technical skills, human resources (i.e., personality type for team composition) is of pivotal importance for developing software which has not been seriously addressed. This study has tried to address this prevailing problem by focusing on patterns of personality types of programmer role monitored with team-leader. Additionally, to draw the attention of practitioners, the results are validated with several classification techniques and results appeared with high accuracy. The study has implications on both software developers and researchers having their interest in role of team composition in software development.;2015;https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7594031;no

**Comment by azhe825** [comment]
@michaelreuter1 
I cannot reproduce your problem with Hall.csv. It loads perfectly on my end.
However, the problem with your test.csv is that it is not comma-separated (it uses ";" to separate each column).

**Comment by azhe825** [comment]
@michaelreuter1 
And you can try removing this file: [src/memory/Hall.pickle](https://github.com/fastread/src/blob/master/) before loading Hall.csv to see if the problem is caused by pickle.

**Comment by michaelreuter1** [comment]
Thanks for the response -- of, course, my own file was messed up. I fixed my file, and it worked. Interestingly, the problem with Hall.csv persisted.

**Comment by michaelreuter1** [comment]
And removing the pickle fixed that as well -- thank you!
