### ISSUE TITLE
Issue running http://localhost:5000/

### ISSUE THREAD

**Issue by sameehaf23** [fastread/src#7]
I followed the steps as directed and when I try to run http://localhost:5000/ on my browser it does not work. I get this error message:
<img width="854" alt="Screen Shot 2022-04-11 at 5 13 52 PM" src="https://user-images.githubusercontent.com/103461591/162834466-c6624bf4-a3ab-477c-88f6-ed33f20a310d.png">

**Comment by azhe825** [comment]
This might due to the reason that some other program is using the port 5000. Please try changing the port flask runs to an idle one in the last line of src/index.py. 

Do a git pull first since I have updated the src/index.py file to include the argument for port.

Thank you!

**Comment by sameehaf23** [comment]
Thank you! It works for me now.
